server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: dressuurMicroservice
          uri: http://localhost:9002/
          predicates:
            - Path=/dressuur/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, *
        - id: authMicroservice
          uri: http://platform-authentication-service:9003/
          predicates:
            - Path=/auth/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, *

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka
#  instance:
#    hostname: gatewayserver

