server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: dressuurMicroservice
          uri: http://10.0.37.227:9002/
          predicates:
            - Path=/dressuur/**
        - id: authMicroservice
          uri: http://10.0.154.30:9003/
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://10.0.28.155:8761/eureka
  instance:
    hostname: gatewayserver

